version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: postgres-container
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=car_allocator
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
    volumes:
      - ./.volumes/database:/var/lib/postgresql/data
